version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: redmine_password
      POSTGRES_DB: redmine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redmine:
    image: redmine:latest
    restart: always
    depends_on:
      - postgres
    environment:
      REDMINE_DB_POSTGRES: postgres
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine_password
    ports:
      - "3001:3000"
    volumes:
      - ./redmine/plugins:/usr/src/redmine/plugins
      - ./redmine/themes:/usr/src/redmine/public/themes
      - ./redmine/files:/usr/src/redmine/files
