production:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      address: smtp.gmail.com
      port: 587
      domain: gmail.com
      authentication: :login
      user_name: testgabriel44@gmail.com
      password: "yfwy ykxq bwcs dtlu"
  
  incoming_emails:
    enabled: true
    protocol: imap
    host: imap.gmail.com
    port: 993
    ssl: true
    username: testgabriel44@gmail.com
    password: "yfwy ykxq bwcs dtlu"
    folder: INBOX
    default_tracker: Support
    project: support
    unknown_user: create
    no_permission_check: 1
    allow_override: all

  attachments_storage_path: /usr/src/redmine/files